spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/med_app_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update # O Spring vai criar as tabelas sozinho!
    show-sql: true